# credentialctl.ps1 -- per-project encrypted vault for project secrets + non-sensitive config.
#
# Key model (trusted-local-machine + cross-machine rebind):
#   * Master secret = a high-entropy key AUTO-GENERATED by init and shown once as MASTER KEY.
#     It is the SOLE key to decrypt (never stored in plaintext) and is portable across machines.
#     Non-interactive/CI may override init with $env:credentialctl_PASSPHRASE (back-compat).
#   * KEK = PBKDF2-HMAC-SHA256(master, salt, 600000 iters) -- derived on demand, never on disk.
#   * On each machine a per-machine unlock blob <root>/unlock/<machine-id>.bin holds
#     DPAPI(CurrentUser, KEK). Same user + same machine => auto-unlock with no input.
#     Move the vault to another machine => re-enter the master once => a new blob is written
#     and that machine auto-unlocks thereafter (many machines can each have a blob).
#   * Entries are envelope-encrypted: a random DEK per entry wraps the value (AES-256-GCM),
#     and the DEK is wrapped by the KEK. Placeholder-by-default, --env/--reveal to emit value.
#   * A project carries a scoped token + scope; the agent lists/reads only in-scope keys.
#   * Every read is audited.
#
# Data root: $env:credentialctl_HOME, else the nearest project .credential (walk up from cwd),
#            else <cwd>\.credential. Keep .credential gitignored; data stays in the project.
#
# Everything is PowerShell 7 (pwsh). No external binaries required.

param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Argv)

$ErrorActionPreference = 'Stop'
$Script:VERSION = '2.1.0'

# ---------------------------------------------------------------- helpers
function Write-Err([string]$m) { [Console]::Error.WriteLine("credentialctl: $m") }
function Fail([string]$m, [int]$code = 1) { Write-Err $m; exit $code }

function Find-Upward([string]$relPath) {
    $c = (Get-Location).Path
    while ($c) {
        if (Test-Path (Join-Path $c $relPath)) { return $c }
        $parent = Split-Path $c -Parent
        if (-not $parent -or $parent -eq $c) { break }
        $c = $parent
    }
    return $null
}
function Get-VaultRoot {
    if ($env:credentialctl_HOME -and $env:credentialctl_HOME.Trim()) { return $env:credentialctl_HOME }
    $d = Find-Upward '.credential\credential.meta.json'
    if ($d) { return (Join-Path $d '.credential') }
    return (Join-Path (Get-Location) '.credential')
}

function Get-RandBytes([int]$n) {
    $b = New-Object byte[] $n
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($b); $rng.Dispose()
    return $b
}
function To-B64([byte[]]$b) { return [Convert]::ToBase64String($b) }
function From-B64([string]$s) { return [Convert]::FromBase64String($s) }
function To-B64Url([byte[]]$b) { return ([Convert]::ToBase64String($b)).Replace('+','-').Replace('/','_').TrimEnd('=') }
function Utf8([string]$s) { return [Text.Encoding]::UTF8.GetBytes($s) }
function FromUtf8([byte[]]$b) { return [Text.Encoding]::UTF8.GetString($b) }
function Sha256Hex([string]$s) {
    $h = [System.Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)))).Replace('-','').ToLower() }
    finally { $h.Dispose() }
}

# --- Windows DPAPI (user+machine bound; this is the "login auto-unlock" mechanism) ---
function Protect-Dpapi([byte[]]$bytes, [string]$scopeName) {
    Add-Type -AssemblyName System.Security -ErrorAction Stop
    $scope = if ($scopeName -eq 'LocalMachine') { [System.Security.Cryptography.DataProtectionScope]::LocalMachine }
             else { [System.Security.Cryptography.DataProtectionScope]::CurrentUser }
    return [System.Security.Cryptography.ProtectedData]::Protect($bytes, $null, $scope)
}
function Unprotect-Dpapi([byte[]]$blob) {
    Add-Type -AssemblyName System.Security -ErrorAction Stop
    return [System.Security.Cryptography.ProtectedData]::Unprotect($blob, $null, [System.Security.Cryptography.DataProtectionScope]::CurrentUser)
}

# --- AES-256-GCM (built-in .NET) ---
function Invoke-AesGcmEncrypt([byte[]]$key, [byte[]]$nonce, [byte[]]$plain) {
    if ($key.Length -ne 32 -or $nonce.Length -ne 12) { throw 'invalid AES-GCM key/nonce size' }
    $cipher = New-Object byte[] $plain.Length; $tag = New-Object byte[] 16
    $gcm = [System.Security.Cryptography.AesGcm]::new($key, 16)
    try { $gcm.Encrypt($nonce, $plain, $cipher, $tag) } finally { $gcm.Dispose() }
    return @{ cipher = $cipher; tag = $tag }
}
function Invoke-AesGcmDecrypt([byte[]]$key, [byte[]]$nonce, [byte[]]$cipher, [byte[]]$tag) {
    if ($key.Length -ne 32 -or $nonce.Length -ne 12) { throw 'invalid AES-GCM key/nonce size' }
    $plain = New-Object byte[] $cipher.Length
    $gcm = [System.Security.Cryptography.AesGcm]::new($key, 16)
    try { $gcm.Decrypt($nonce, $cipher, $tag, $plain) } finally { $gcm.Dispose() }
    return $plain
}

# --- master-key derivation (PBKDF2-HMAC-SHA256; Argon2id needs a non-.NET lib) ---
function Derive-Kek([string]$master, [byte[]]$salt, [int]$iter) {
    $pw = [Text.Encoding]::UTF8.GetBytes($master)
    return [System.Security.Cryptography.Rfc2898DeriveBytes]::Pbkdf2($pw, $salt, $iter, [System.Security.Cryptography.HashAlgorithmName]::SHA256, 32)
}
function Get-MachineId {
    $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
    return (Sha256Hex (($env:COMPUTERNAME + '|' + $sid))).Substring(0, 20)
}

# --- vault paths ---
function Get-MetaPath([string]$root) { return (Join-Path $root 'credential.meta.json') }
function Get-UnlockDir([string]$root) { return (Join-Path $root 'unlock') }
function Get-StorePath([string]$root) { return (Join-Path $root 'credential.json') }

function Read-Meta([string]$root) {
    $p = Get-MetaPath $root
    if (-not (Test-Path $p)) { Fail "vault not initialized (missing $p). run: credentialctl init" }
    return ((Get-Content $p -Raw) | ConvertFrom-Json -AsHashtable)
}
function Write-Meta([string]$root, $meta) {
    if (-not (Test-Path $root)) { [System.IO.Directory]::CreateDirectory($root) | Out-Null }
    $p = Get-MetaPath $root; $tmp = "$p.tmp"
    [System.IO.File]::WriteAllText($tmp, (ConvertTo-Json $meta -Depth 8), [Text.Encoding]::UTF8)
    Move-Item -Force -Path $tmp -Destination $p
}
function Read-Store([string]$root) {
    $p = Get-StorePath $root
    if (-not (Test-Path $p)) { Fail "vault not initialized (missing $p). run: credentialctl init" }
    return ((Get-Content $p -Raw) | ConvertFrom-Json -AsHashtable)
}
function Write-Store([string]$root, $store) {
    if (-not (Test-Path $root)) { [System.IO.Directory]::CreateDirectory($root) | Out-Null }
    $p = Get-StorePath $root; $tmp = "$p.tmp"
    [System.IO.File]::WriteAllText($tmp, (ConvertTo-Json $store -Depth 12), [Text.Encoding]::UTF8)
    Move-Item -Force -Path $tmp -Destination $p
}
function Add-Audit($store, [string]$op, [string]$project, [string]$key, [bool]$reveal) {
    $entry = @{ t = (Get-Date -Format o); op = $op; project = $project; key = $key; reveal = $reveal }
    if (-not $store.ContainsKey('audit') -or $null -eq $store['audit']) { $store['audit'] = @() }
    $store['audit'] = @($store['audit']) + $entry
    if ($store['audit'].Count -gt 2000) { $store['audit'] = $store['audit'][ -2000..-1 ] }
}

# --- key check (verifies a correct passphrase/recovery code by decrypting a known value) ---
function New-KekCheck($kek) {
    $nonce = Get-RandBytes 12
    $res = Invoke-AesGcmEncrypt $kek $nonce (Utf8 'credentialctl:keycheck')
    return @{ nonce = (To-B64 $nonce); val = (To-B64 $res.cipher); tag = (To-B64 $res.tag) }
}
function Test-KekCheck($kek, $check) {
    try {
        $plain = FromUtf8 (Invoke-AesGcmDecrypt $kek (From-B64 $check['nonce']) (From-B64 $check['val']) (From-B64 $check['tag']))
        return ($plain -eq 'credentialctl:keycheck')
    } catch { return $false }
}

# --- per-machine unlock blobs ---
function Write-UnlockBlob([string]$root, $kek) {
    $dir = Get-UnlockDir $root
    if (-not (Test-Path $dir)) { [System.IO.Directory]::CreateDirectory($dir) | Out-Null }
    $mid = Get-MachineId
    [System.IO.File]::WriteAllBytes((Join-Path $dir "$mid.bin"), (Protect-Dpapi $kek 'CurrentUser'))
}
function Try-UnlockBlobs([string]$root) {
    $dir = Get-UnlockDir $root
    if (-not (Test-Path $dir)) { return $null }
    foreach ($f in (Get-ChildItem $dir -Filter '*.bin' -ErrorAction SilentlyContinue)) {
        try {
            $kek = Unprotect-Dpapi ([System.IO.File]::ReadAllBytes($f.FullName))
            if ($kek -and $kek.Length -eq 32) { return $kek }   # only this user+machine's blob decrypts
        } catch { continue }
    }
    return $null
}

# --- master secret input ---
function Read-SecretPrompt([string]$label) {
    $sec = Read-Host -AsSecureString $label
    if ($null -eq $sec) { return $null }
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    try { return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
    finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}
function Get-UnlockSecret {
    if ($env:credentialctl_PASSPHRASE) { return $env:credentialctl_PASSPHRASE }
    if ([Console]::IsInputRedirected) { return ([Console]::In.ReadToEnd()).TrimEnd("`r","`n") }
    return (Read-SecretPrompt 'Vault passphrase / recovery code (hidden)')
}
function Get-NewPassphrase {
    if ($env:credentialctl_PASSPHRASE) { return $env:credentialctl_PASSPHRASE }
    if ([Console]::IsInputRedirected) { return ([Console]::In.ReadToEnd()).TrimEnd("`r","`n") }
    $p1 = Read-SecretPrompt 'Set vault passphrase (hidden)'
    if (-not $p1) { Fail 'no passphrase provided' }
    $p2 = Read-SecretPrompt 'Confirm passphrase (hidden)'
    if ($p1 -ne $p2) { Fail 'passphrases do not match' }
    return $p1
}

# --- unlock: try per-machine blobs; else prompt master once; rebind this machine ---
function Unlock-Vault([string]$root) {
    $kek = Try-UnlockBlobs $root
    if ($kek) { return $kek }
    $secret = Get-UnlockSecret
    if (-not $secret) { Fail 'passphrase required (this machine is not bound; re-enter the master once)' }
    $meta = Read-Meta $root
    $kek = Derive-Kek $secret (From-B64 $meta['salt']) ([int]$meta['iter'])
    if (-not (Test-KekCheck $kek $meta['check'])) { Fail 'incorrect passphrase / recovery code' }
    Write-UnlockBlob $root $kek   # bind this machine so it auto-unlocks next time
    return $kek
}

# --- project auth / scope ---
function Resolve-Project($store, [string]$project, [string]$token) {
    if (-not $store['projects'].ContainsKey($project)) { Fail "unknown project '$project'" }
    $proj = $store['projects'][$project]
    if (-not $token) { Fail "token required for project '$project'" }
    if ((Sha256Hex $token) -ne $proj['tokenHash']) { Fail "invalid token for project '$project'" }
    return $proj
}
function In-Scope($proj, [string]$key) {
    $scope = @($proj['scope']) -ne $null
    if ($scope -contains $key) { return $true }
    foreach ($s in $scope) { if ($key -like $s) { return $true } }
    return $false
}

# ---------------------------------------------------------------- arg parsing
function Parse-Params($argv, $argvStart) {
    $opts = @{}; $positional = @()
    for ($i = $argvStart; $i -lt $argv.Count; $i++) {
        $a = [string]$argv[$i]
        if ($a -match '^--?([\w-]+)$') {
            $name = $Matches[1].ToLower()
            if ($i + 1 -lt $argv.Count -and ([string]$argv[$i+1] -notmatch '^--?[\w-]+$')) { $opts[$name] = [string]$argv[$i+1]; $i++ }
            else { $opts[$name] = $true }
        } else { $positional += $a }
    }
    return @{ opts = $opts; positional = $positional }
}
function Read-ValueInput($opts, [bool]$secret) {
    if ($opts.ContainsKey('file')) {
        $fp = [string]$opts['file']
        if (-not (Test-Path $fp)) { Fail "value file not found: $fp" }
        return ([System.IO.File]::ReadAllText($fp)).TrimEnd("`r","`n")
    }
    if ($opts.ContainsKey('value')) {
        if ($secret) { Write-Err 'warning: value passed via --value sits in process argv; prefer --file / stdin' }
        return [string]$opts['value']
    }
    if ([Console]::IsInputRedirected) { return ([Console]::In.ReadToEnd()).TrimEnd("`r","`n") }
    if ($secret) {
        $sec = Read-Host -AsSecureString 'Value (hidden)'
        if ($null -eq $sec) { return $null }
        $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
        try { return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
        finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
    }
    return (Read-Host 'Value')
}
function Get-Opt($opts, [string]$name) { if ($opts.ContainsKey($name)) { return $opts[$name] } return $null }

# ---------------------------------------------------------------- commands
function Invoke-Init($root, $opts) {
    if (Test-Path (Get-MetaPath $root)) { Fail 'vault already initialized' }
    if (-not (Test-Path $root)) { [System.IO.Directory]::CreateDirectory($root) | Out-Null }
    # Master secret: high-entropy key auto-generated by init (the SOLE key, portable across machines).
    # Non-interactive/CI must provide it via credentialctl_PASSPHRASE (then init does NOT print a secret).
    $autoGen = $true; $master = $null
    if ($env:credentialctl_PASSPHRASE -and $env:credentialctl_PASSPHRASE.Trim()) {
        $master = $env:credentialctl_PASSPHRASE; $autoGen = $false
    }
    if (-not $master) { $master = To-B64Url (Get-RandBytes 32) }
    $salt = Get-RandBytes 16; $iter = 600000
    $kek = Derive-Kek $master $salt $iter
    $meta = @{ version = 2; kdf = 'pbkdf2-sha256'; iter = $iter; salt = (To-B64 $salt); check = (New-KekCheck $kek); created = (Get-Date -Format o) }
    Write-Meta $root $meta
    Write-UnlockBlob $root $kek
    $store = @{ version = 1; created = (Get-Date -Format o); projects = @{}; entries = @{}; audit = @() }
    Write-Store $root $store
    Write-Output "vault initialized at $root (KEK = PBKDF2(master, salt, 600k); this machine bound via DPAPI)"
    if ($autoGen) {
        Write-Output ""
        Write-Output "############################################################"
        Write-Output "#  MASTER KEY (the SOLE key to decrypt this vault - SAVE IT)  #"
        Write-Output "#  Re-enter it once on a new machine to re-bind + recover.    #"
        Write-Output "############################################################"
        Write-Output $master
        Write-Output ""
        Write-Output "Store this master key in your password manager. It is the only key that"
        Write-Output "unlocks after a host change (this machine auto-unlocks via DPAPI blob)."
        Write-Output "If you lose it AND every machine blob, the vault cannot be recovered by design."
    } else {
        Write-Output "master secret taken from credentialctl_PASSPHRASE (bound this machine via DPAPI)."
    }
}

function Write-ProjectConfigFile([string]$path, [string]$project, [string]$token, $scope) {
    $dir = Split-Path $path -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    [System.IO.File]::WriteAllText($path, "# vault project binding (auto-written by credentialctl)`nproject: $project`ntoken: $token`nscope: $(($scope -join ', '))`n", [Text.Encoding]::UTF8)
}
function Append-AgentMdBlock([string]$path, [string]$project, [string]$token, $scope) {
    $dir = Split-Path $path -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $block = "## vault`n- project: $project`n- token: $token`n- scope: $($scope -join ', ')`n"
    if (Test-Path $path) { Add-Content -Path $path -Value ("`n" + $block) -Encoding UTF8 }
    else { [System.IO.File]::WriteAllText($path, $block, [Text.Encoding]::UTF8) }
}

function Invoke-ProjectInit($root, $opts, $positional) {
    if ($positional.Count -lt 1) { Fail 'usage: credentialctl project init <project> [--scope k1,k2,...] [--agent-md <path>] [--config <path>]' }
    $project = $positional[0]
    $store = Read-Store $root
    if ($store['projects'].ContainsKey($project)) { Fail "project '$project' already exists (use 'project token' to rotate)" }
    $scopeRaw = [string](Get-Opt $opts 'scope')
    $scopeList = [System.Collections.Generic.List[string]]::new()
    if ($scopeRaw) { foreach ($t in ($scopeRaw -split ',')) { $t2 = $t.Trim(); if ($t2) { $scopeList.Add($t2) } } }
    $token = ([BitConverter]::ToString((Get-RandBytes 32))).Replace('-','').ToLower()
    $store['projects'][$project] = @{ tokenHash = (Sha256Hex $token); scope = $scopeList.ToArray(); created = (Get-Date -Format o) }
    Write-Store $root $store
    $configPath = [string](Get-Opt $opts 'config')
    if ($configPath) { Write-ProjectConfigFile $configPath $project $token $scopeList.ToArray() }
    $agentMd = [string](Get-Opt $opts 'agent-md')
    if ($agentMd) { Append-AgentMdBlock $agentMd $project $token $scopeList.ToArray() }
    Write-Output ("[bootstrap] project '$project' created; token written to agent-md/config. token: $token")
}
function Invoke-ProjectAdd($root, $opts, $positional) {
    if ($positional.Count -lt 1) { Fail 'usage: credentialctl project add <project> [--scope k1,k2,...]' }
    $project = $positional[0]
    $store = Read-Store $root
    if ($store['projects'].ContainsKey($project)) { Fail "project '$project' already exists" }
    $scopeRaw = [string](Get-Opt $opts 'scope')
    $scopeList = [System.Collections.Generic.List[string]]::new()
    if ($scopeRaw) { foreach ($t in ($scopeRaw -split ',')) { $t2 = $t.Trim(); if ($t2) { $scopeList.Add($t2) } } }
    $token = [string](Get-Opt $opts 'token')
    if (-not $token) { $token = ([BitConverter]::ToString((Get-RandBytes 32))).Replace('-','').ToLower() }
    $store['projects'][$project] = @{ tokenHash = (Sha256Hex $token); scope = $scopeList.ToArray(); created = (Get-Date -Format o) }
    Write-Store $root $store
    Write-Output $token
}
function Invoke-ProjectToken($root, $opts, $positional) {
    if ($positional.Count -lt 1) { Fail 'usage: credentialctl project token <project> [--agent-md <path>] [--config <path>]' }
    $project = $positional[0]
    $store = Read-Store $root
    if (-not $store['projects'].ContainsKey($project)) { Fail "unknown project '$project'" }
    $token = ([BitConverter]::ToString((Get-RandBytes 32))).Replace('-','').ToLower()
    $store['projects'][$project]['tokenHash'] = (Sha256Hex $token)
    Write-Store $root $store
    $configPath = [string](Get-Opt $opts 'config')
    if ($configPath) { Write-ProjectConfigFile $configPath $project $token @($store['projects'][$project]['scope']) }
    $agentMd = [string](Get-Opt $opts 'agent-md')
    if ($agentMd) { Append-AgentMdBlock $agentMd $project $token @($store['projects'][$project]['scope']) }
    Write-Output ("[rotate] project '$project' token rotated. token: $token")
}

function Resolve-ProjectToken([string]$project) {
    if ($env:credentialctl_TOKEN) { return $env:credentialctl_TOKEN }
    $d = Find-Upward '.credential\config'
    if ($d) {
        $txt = [System.IO.File]::ReadAllText((Join-Path $d '.credential\config'))
        if ($txt -match '(?m)^token:\s*(\S+)') { return $Matches[1] }
    }
    $c2 = Join-Path (Get-Location) '.credential.config'
    if (Test-Path $c2) { if ((Get-Content $c2 -Raw) -match '(?m)^token:\s*(\S+)') { return $Matches[1] } }
    return $null
}
function Get-EffectiveToken($opts, [string]$project) {
    $tok = [string](Get-Opt $opts 't'); if (-not $tok) { $tok = [string](Get-Opt $opts 'token') }
    if (-not $tok) { $tok = Resolve-ProjectToken $project }
    return $tok
}

function Invoke-Add($root, $opts, $positional) {
    if ($positional.Count -lt 2) { Fail 'usage: credentialctl add <project> <key> [--secret|--config] [--plain]' }
    $project = $positional[0]; $key = $positional[1]
    $store = Read-Store $root
    if (-not $store['projects'].ContainsKey($project)) { Fail "unknown project '$project'" }
    $isSecret = -not ($opts.ContainsKey('config'))
    $kind = if ($isSecret) { 'secret' } else { 'config' }
    $plain = $opts.ContainsKey('plain')
    $value = Read-ValueInput $opts $isSecret
    if ($null -eq $value) { Fail 'no value provided' }
    $entryKey = "$project/$key"
    if ($plain -and -not $isSecret) {
        $entry = @{ project = $project; key = $key; kind = 'config'; enc = 'plain'; plain = $value; updated = (Get-Date -Format o) }
    } else {
        $kek = Unlock-Vault $root
        $dek = Get-RandBytes 32
        $dekNonce = Get-RandBytes 12; $wrap = Invoke-AesGcmEncrypt $kek $dekNonce $dek
        $valNonce = Get-RandBytes 12; $valRes = Invoke-AesGcmEncrypt $dek $valNonce (Utf8 $value)
        $entry = @{ project = $project; key = $key; kind = $kind; enc = 'aes-256-gcm'
            dek = (To-B64 $wrap.cipher); dekNonce = (To-B64 $dekNonce); dekTag = (To-B64 $wrap.tag)
            val = (To-B64 $valRes.cipher); valNonce = (To-B64 $valNonce); valTag = (To-B64 $valRes.tag)
            updated = (Get-Date -Format o) }
        $dek = $null
    }
    $store['entries'][$entryKey] = $entry
    Add-Audit $store 'set' $project $key $false
    Write-Store $root $store
    Write-Output "stored $entryKey ($kind)"
}

function Invoke-Get($root, $opts, $positional) {
    if ($positional.Count -lt 2) { Fail 'usage: credentialctl get <project> <key> [-t token] [--reveal] [--env NAME]' }
    $project = $positional[0]; $key = $positional[1]
    $token = Get-EffectiveToken $opts $project
    $reveal = $opts.ContainsKey('reveal') -or $opts.ContainsKey('re')
    $envName = [string](Get-Opt $opts 'env')
    $store = Read-Store $root
    $proj = Resolve-Project $store $project $token
    if (-not (In-Scope $proj $key)) { Add-Audit $store 'deny' $project $key $false; Write-Store $root $store; Fail "key '$key' is not in project scope for '$project'" }
    $entryKey = "$project/$key"
    if (-not $store['entries'].ContainsKey($entryKey)) { Fail "no entry '$entryKey'" }
    $entry = $store['entries'][$entryKey]
    $needValue = $reveal -or $envName
    $value = $null
    if ($entry['enc'] -eq 'plain') { $value = [string]$entry['plain'] }
    elseif ($needValue) {
        $kek = Unlock-Vault $root
        $dek = Invoke-AesGcmDecrypt $kek (From-B64 $entry['dekNonce']) (From-B64 $entry['dek']) (From-B64 $entry['dekTag'])
        $value = FromUtf8 (Invoke-AesGcmDecrypt $dek (From-B64 $entry['valNonce']) (From-B64 $entry['val']) (From-B64 $entry['valTag']))
    }
    if (-not $needValue) { Add-Audit $store 'get' $project $key $false; Write-Store $root $store; Write-Output "<CREDENTIAL:$entryKey>"; return }
    Add-Audit $store ($(if ($reveal) { 'reveal' } else { 'env' })) $project $key $true; Write-Store $root $store
    if ($envName) { Write-Output ("`$env:$envName = '" + $value.Replace("'","''") + "'") }
    else { Write-Output $value }
}

function Invoke-List($root, $opts, $positional) {
    if ($positional.Count -lt 1) { Fail 'usage: credentialctl list <project> [-t token]' }
    $project = $positional[0]
    $token = Get-EffectiveToken $opts $project
    $store = Read-Store $root
    $proj = Resolve-Project $store $project $token
    $keys = New-Object System.Collections.Generic.List[string]
    foreach ($ek in $store['entries'].Keys) {
        if ($ek.StartsWith("$project/")) { $k = $ek.Substring($project.Length + 1); if (In-Scope $proj $k) { $keys.Add($k) } }
    }
    Write-Output (($keys | Sort-Object -Unique) -join "`n")
}

function Invoke-Rotate($root, $opts, $positional) {
    if ($positional.Count -lt 2) { Fail 'usage: credentialctl rotate <project> <key> [-t token]' }
    $project = $positional[0]; $key = $positional[1]
    $token = Get-EffectiveToken $opts $project
    $store = Read-Store $root
    $proj = Resolve-Project $store $project $token
    if (-not (In-Scope $proj $key)) { Fail "key '$key' is not in project scope" }
    $entryKey = "$project/$key"
    if (-not $store['entries'].ContainsKey($entryKey)) { Fail "no entry '$entryKey'" }
    $entry = $store['entries'][$entryKey]
    if ($entry['enc'] -eq 'plain') { Fail 'plain config entry cannot be rotated as a secret' }
    $kek = Unlock-Vault $root
    $oldDek = Invoke-AesGcmDecrypt $kek (From-B64 $entry['dekNonce']) (From-B64 $entry['dek']) (From-B64 $entry['dekTag'])
    $plain = FromUtf8 (Invoke-AesGcmDecrypt $oldDek (From-B64 $entry['valNonce']) (From-B64 $entry['val']) (From-B64 $entry['valTag']))
    $newDek = Get-RandBytes 32; $dekNonce = Get-RandBytes 12; $wrap = Invoke-AesGcmEncrypt $kek $dekNonce $newDek
    $valNonce = Get-RandBytes 12; $valRes = Invoke-AesGcmEncrypt $newDek $valNonce (Utf8 $plain)
    $entry['dek'] = To-B64 $wrap.cipher; $entry['dekNonce'] = To-B64 $dekNonce; $entry['dekTag'] = To-B64 $wrap.tag
    $entry['val'] = To-B64 $valRes.cipher; $entry['valNonce'] = To-B64 $valNonce; $entry['valTag'] = To-B64 $valRes.tag
    $entry['updated'] = Get-Date -Format o
    Add-Audit $store 'rotate' $project $key $false
    Write-Store $root $store
    Write-Output "rotated $entryKey"
}

function Invoke-Audit($root, $opts, $positional) {
    $projForTok = if ($positional.Count -gt 0) { $positional[0] } else { '' }
    $token = Get-EffectiveToken $opts $projForTok
    $store = Read-Store $root
    foreach ($e in @($store['audit'])) { Write-Output ("{0}  {1,-6}  {2}/{3}  reveal={4}" -f $e['t'], $e['op'], $e['project'], $e['key'], $e['reveal']) }
}

function Invoke-MachineBind($root, $opts) { Unlock-Vault $root | Out-Null; Write-Output "bound this machine (unlock/<machine-id>.bin present)" }
function Invoke-MachineUnbind($root, $opts) {
    $dir = Get-UnlockDir $root; $mid = Get-MachineId; $f = Join-Path $dir "$mid.bin"
    if (Test-Path $f) { Remove-Item $f -Force; Write-Output "removed unlock blob for this machine ($mid)" }
    else { Write-Output "no unlock blob for this machine ($mid)" }
}
function Invoke-MachineList($root, $opts) {
    $dir = Get-UnlockDir $root
    if (Test-Path $dir) { Get-ChildItem $dir -Filter '*.bin' -ErrorAction SilentlyContinue | ForEach-Object { Write-Output $_.BaseName } } else { Write-Output '(none)' }
}
function Invoke-Version { Write-Output "credentialctl $Script:VERSION" }

# ---------------------------------------------------------------- dispatch
$root = Get-VaultRoot
$command = if ($Argv.Count -gt 0) { [string]$Argv[0].ToLower() } else { '' }
$parsed = Parse-Params $Argv 1
$opts = $parsed.opts; $pos = $parsed.positional

if (-not $command -or $command -eq 'help') {
    @"
credentialctl v$($Script:VERSION) -- per-project encrypted vault (passphrase-derived KEK + per-machine DPAPI unlock)

usage:
  credentialctl init                                                     # create vault; auto-generates MASTER key (SAVE it) - the sole key, recovers across machines
  credentialctl version
  credentialctl project init <project> [--scope k1,k2,...] [--agent-md <path>] [--config <path>]
  credentialctl project add <project> [--scope k1,k2,...]
  credentialctl project token <project> [--agent-md <path>] [--config <path>]
  credentialctl add <project> <key> [--secret|--config] [--plain] [--file <path>|--value v|piped]
  credentialctl get <project> <key> [-t <token>] [--reveal] [--env NAME]
  credentialctl list <project> [-t <token>]
  credentialctl rotate <project> <key> [-t <token>]
  credentialctl audit
  credentialctl machine bind | unbind | list

env:  credentialctl_HOME   vault root (default: nearest project .credential, or <cwd>\.credential)
      credentialctl_PASSPHRASE   master secret override for init (else init auto-generates a MASTER key)
      credentialctl_TOKEN        project token (else <cwd> path .credential\config auto)

master/unlock:  KEK = PBKDF2(master, salt, 600k). The MASTER key is auto-generated by init and shown once
                - save it (password manager). Same user+machine auto-unlocks via DPAPI blob; a NEW machine
                re-enters the MASTER key once and gets its own blob.
default get:    <CREDENTIAL:proj/key> placeholder; only --env/--reveal emit the real value.
Windows note:  invoke as a script FILE, never inline pwsh -Command (Defender AMSI may flag crypto).
"@ | ForEach-Object { Write-Output $_ }
    exit 0
}

switch ($command) {
    'init'       { Invoke-Init $root $opts }
    'version'    { Invoke-Version }
    'project'    {
        if ($pos.Count -gt 0) {
            $sub = $pos[0]; $subargs = @($pos[1..($pos.Count-1)])
            switch ($sub) {
                'init'  { Invoke-ProjectInit $root $opts $subargs }
                'add'   { Invoke-ProjectAdd $root $opts $subargs }
                'token' { Invoke-ProjectToken $root $opts $subargs }
                default { Fail 'usage: credentialctl project <init|add|token> <project> [--scope ...] [--agent-md <path>] [--config <path>]' }
            }
        } else { Fail 'usage: credentialctl project <init|add|token> <project> [--scope ...]' }
    }
    'add'        { Invoke-Add $root $opts $pos }
    'get'        { Invoke-Get $root $opts $pos }
    'list'       { Invoke-List $root $opts $pos }
    'rotate'     { Invoke-Rotate $root $opts $pos }
    'audit'      { Invoke-Audit $root $opts $pos }
    'machine'    {
        if ($pos.Count -gt 0) {
            switch ($pos[0]) { 'bind' { Invoke-MachineBind $root $opts } 'unbind' { Invoke-MachineUnbind $root $opts } 'list' { Invoke-MachineList $root $opts } default { Fail 'usage: credentialctl machine bind|unbind|list' } }
        } else { Fail 'usage: credentialctl machine bind|unbind|list' }
    }
    default      { Fail "unknown command '$command'" }
}
